src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TicketRepository::class)
 */
class Ticket
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="tickets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $intitule;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $niveau;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $ClosedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $etat;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $resolution;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): self
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNiveau(): ?int
    {
        return $this->niveau;
    }

    public function setNiveau(int $niveau): self
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getClosedAt(): ?\DateTimeInterface
    {
        return $this->ClosedAt;
    }

    public function setClosedAt(?\DateTimeInterface $ClosedAt): self
    {
        $this->ClosedAt = $ClosedAt;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getResolution(): ?string
    {
        return $this->resolution;
    }

    public function setResolution(?string $resolution): self
    {
        $this->resolution = $resolution;

        return $this;
    }
}

src/Form/TicketType.php
<?php

namespace App\Form;

use App\Entity\Ticket;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class TicketType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('intitule', TextType::class, ['label' => 'Intitulé : '])
            ->add('description', TextareaType::class, ['label' => 'Description : '])
            ->add('niveau', ChoiceType::class, ['label' => 'Niveau d\'urgence : ', 'choices' => [
                '1' => 1,
                '2' => 2,
                '3' => 3,
                '4' => 4,
                '5' => 5
            ],
            ])
            ->add('submit', SubmitType::class, ['label' => 'Ajouter'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ticket::class,
        ]);
    }
}

src/Controller/TicketController.php
<?php

namespace App\Controller;

use DateTime;
use DateTimeZone;
use App\Entity\Client;
use App\Entity\Ticket;
use App\Form\TicketType;
use App\Repository\ClientRepository;
use App\Repository\TicketRepository;
use Symfony\Component\Form\FormBuilder;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\FormBuilderInterface;
use Tetranz\Select2EntityBundle\Form\Type\Select2EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TicketController extends AbstractController
{

    /**
     * @Route("/ticket", name="ticket_index")
     */
    public function index(TicketRepository $ticketRepo, ClientRepository $clientRepo, PaginatorInterface $paginator, Request $request)
    {
        $datas = $ticketRepo->findBy([], ['createdAt' => 'DESC']);
        $clients = $clientRepo->findAll();

        $tickets = $paginator->paginate(
            $datas,
            $request->query->getInt('page', 1),
            4
        );

        return $this->render('ticket/index.html.twig', [
            'tickets' => $tickets,
            'clients' => $clients,
        ]);
    }

    /**
     * @Route("/ticket/add{id}", name="ticket_add_client")
     */
    public function addClient(ClientRepository $clientRepo, Client $client, Request $request, EntityManagerInterface $manager)
    {
        $client = $clientRepo->find($client);
        $ticket = new Ticket();

        $form = $this->createForm(TicketType::class, $ticket);
        $form->handleRequest($request);
        $ticket->setClient($client);
        $ticket->setCreatedAt(new DateTime('NOW', new DateTimeZone('Europe/Paris')));
        $ticket->setEtat('Ouvert');

        if ($form->isSubmitted() && $form->isValid()) {
             $manager->persist($ticket);
             $manager->flush();

             return $this->redirectToRoute('ticket_index');
        }

        return $this->render('ticket/addTicket.html.twig', [
            'client' => $client,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/ticket/choix", name="ticket_choix")
     */
    public function choixClient(Request $request)
    {
        $id = $request->query->get('clients');
        
        return $this->redirectToRoute('ticket_add_client',  ['id' => $id]);
    }

    /** 
     * @Route("/ticket{id}", name="ticket_show")
     */
    public function showDevis(Ticket $ticket, ClientRepository $clientRepo)
    {
        $client = $ticket->getClient();
        $client = $clientRepo->findOneBy(['id' => $client->getId()]);
        
        return $this->render('ticket/showTicket.html.twig', [
            'client' => $client,
            'ticket' => $ticket
        ]);
    }

    /** 
     * @Route("/ticket{id}/close", name="ticket_close")
     */
    public function closeDevis(Ticket $ticket, Request $request, EntityManagerInterface $manager)
    {
        $id = $ticket->getId();
        
        $resol = $request->query->get('resolution');
        if(!empty($resol))
        {
            $ticket->setResolution($resol);
            $ticket->setEtat('Fermé');
            $ticket->setClosedAt(new DateTime('NOW', new DateTimeZone('Europe/Paris')));
            $manager->persist($ticket);
            $manager->flush();

            return $this->redirectToRoute('ticket_show',  ['id' => $id]);
        }
    }
}

templates/ticket/addTicket.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau ticket{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {% if client is defined %}
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-header">
                        <p><b>Nom : </b>{{client.nom}} <b>Prénom : </b>{{client.prenom}}</p>
                        {% if client.societe is not null %}
                        <p><b>Société : </b>{{client.societe}}</p>
                        {% endif %}
                        <p><b>Email : </b>{{client.mail}}</p>
                        <p><b>Téléphone : </b>{{client.telephone}}</p>
                    </div>
                    <div class="card-body">
                        {{ form_start(form, {'attr': {'class': 'row'}}) }}
                        <div class="form-group">
                            {{ form_row(form.intitule, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group ml-4">
                            {{ form_row(form.niveau, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_row(form.description, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                    <div class="mx-auto mb-2">
                        {{ form_row(form.submit, {'attr': {'class': 'btn btn-primary'}}) }}
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/ticket/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TicketController!{% endblock %}

{% block body %}
<style>
    .card {
        min-height: 475px;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form action="{{path('ticket_choix')}}">
                <select class='clients custom-select custom-select-lg mb-3' name='clients'>
                    <option selected>Choisir client</option>
                    {% for cli in clients %}
                    <option value="{{cli.id}}">
                        {% if cli.societe is not null %}
                        {{cli.societe}}</option>
                    {% else %}
                    {{cli.nom}} - {{ cli.prenom }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
                <button type="submit" class="btn btn-primary mt-2">Créer ticket</button>
            </form>
        </div>
    </div>
    <div class="row mt-3">
        <div class="card-deck">
            {% if tickets is defined %}
            {% for ticket in tickets %}

            <div class="card" style="width: 18rem;">
                <div {% if ticket.etat == 'Ouvert' %} class="card-header text-center alert-success" {% else %}
                    class="card-header text-center alert alert-danger" {% endif %}>
                    <p><b>Ticket N°{{ticket.id}}</b></p>
                    {% if ticket.client.societe is not null %}
                    <p><b>Société : </b>{{ticket.client.societe}}</p>
                    {% else %}
                    <p><b>Client : </b>{{ticket.client.nom}}</p>
                    {% endif %}
                    <p><b>État ticket : </b>{{ticket.etat}}</p>
                </div>
                <div class="card-body d-flex flex-column">
                    <p><b>Intitulé : </b>{{ticket.intitule}}</p>
                    <p><b>Description : </b>{{ticket.description}}</p>
                    <p><b>Niveau d'urgence : </b>{{ticket.niveau}}/5</p>
                    <p><b>Créé le : </b>{{ticket.createdAt|date("d/m/Y")}}</p>
                    {% if ticket.closedAt is not null %}
                    <p><b>Fermé le : </b>{{ticket.closedAt|date("d/m/Y")}}</p>
                    {% endif %}
                    <div class="mt-auto text-center">

                        <a href="{{path('ticket_show', {'id':ticket.id})}}" class="btn btn-primary">Voir ticket</a>
                    </div>

                </div>
            </div>

            {% endfor %}
            {% endif %}
        </div>
        <div class="mt-3">
            {{ knp_pagination_render(tickets) }}
        </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $('.clients').select2();
    });
</script>
{% endblock %}

templates/ticket/showTicket.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ticket N°{{ticket.id}}{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {% if client is defined %}
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div {% if ticket.etat == 'Ouvert' %} class="card-header text-center alert-success" {% else %}
                        class="card-header text-center alert-danger" {% endif %}>
                        <p><b>Nom : </b>{{client.nom}} <b>Prénom : </b>{{client.prenom}}</p>
                        {% if client.societe is not null %}
                        <p><b>Société : </b>{{client.societe}}</p>
                        {% endif %}
                        <p><b>Email : </b>{{client.mail}}</p>
                        <p><b>Téléphone : </b>{{client.telephone}}</p>
                        <p><b>Créé le : </b>{{ticket.createdAt|date("d/m/Y")}} &nbsp;
                            {% if ticket.closedAt is not null %}
                            <b>Fermé le : </b>{{ticket.closedAt|date("d/m/Y")}}
                            {% endif %}</p>
                    </div>
                    <div class="card-body text-center">
                        <p><b>Intitulé : </b>{{ticket.intitule}}</p>
                        <p><b>Description : </b></p>
                        <p>{{ticket.description}}</p>
                        {% if ticket.resolution is not null %}
                        <p><b>Résolution : </b></p>
                        <p>{{ticket.resolution}}</p>
                        {% else %}
                        <form action="{{path('ticket_close', {'id':ticket.id})}}" class="form-group">
                            <label for="resolution"><b>Résolution du ticket : </b></label>
                            <textarea class="form-control" name="resolution" required></textarea>
                            <button type="submit" class="btn btn-danger mt-3">Fermer le ticket</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}